# Your workflow name.
name: Deploy to B4App.

# Run workflow on every push to main branch.
on:
  push:
    branches: [main]

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2


### ⬇ IMPORTANT PART ⬇ ###

      - name: Deploy B4App
        uses: omurilo/action-back4app@v3.1

        with:

          email: ${{ secrets.B4App_EMAIL }}
          
          accountKey: ${{ secrets.B4App_API_KEY }}

          project: ${{ secrets.B4App_APP_NAME }}

          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web
        